behaviors:
  carMove:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      beta: 5.0e-3
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.99
      num_epoch: 3

    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 256
      num_layers: 3
      memory:
        sequence_length: 64
        memory_size: 256

    
    max_steps: 1.5e6
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: false
    init_path: null

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
